### ISSUE TITLE
Audio stutter on Android Oreo

### ISSUE THREAD

**Issue by ENDYMIION** [brianblakely/atlantis#33]
**Describe the bug**
A clear and concise description of the bug.

Audio stutters, even before opening a ROM

**Did you add the app to the homescreen, if possible?**
The app works best when launched from your homescreen.

Yes

**System Info:**
 - Device: [e.g. iPhone 8 Plus, Laptop]
 - OS: [e.g. iOS 12]
 - Browser [e.g. Chrome, Safari]

Samsung Galaxy S8, Android 8.0 Oreo, Chrome 

**Screenshots**
If applicable, add screenshots to help exhibit the bug.

**Comment by brianblakely** [comment]
@ENDYMIION does this still happen when you turn off rewind in the settings?

**Comment by brianblakely** [comment]
Closing for now due to lack of activity. If this is still an issue, feel free to add a comment, but please be sure to answer the question above.
