### ISSUE TITLE
Emulator won’t open properly, goes only to a white screen. App was added to home screen of an iPhone 6s through safari on iOS 11.4

### ISSUE THREAD

**Issue by Slashfyre** [brianblakely/atlantis#34]
**Describe the bug**
A clear and concise description of the bug.

**Did you add the app to the homescreen, if possible?**
The app works best when launched from your homescreen.

**System Info:**
 - Device: [e.g. iPhone 8 Plus, Laptop]
 - OS: [e.g. iOS 12]
 - Browser [e.g. Chrome, Safari]

**Screenshots**
If applicable, add screenshots to help exhibit the bug.

**Comment by brianblakely** [comment]
I think this is an unfortunate side-effect of a major beta update.  The only way I've been able to solve it is to wipe all website data and start again.
