### ISSUE TITLE
Integration with Homebrew Hub

### ISSUE THREAD

**Issue by avivace** [brianblakely/atlantis#35]
Oh hey,

Mantainer of [Homebrew Hub](https://gbhh.avivace.com/) here ([repo](https://github.com/gbdev/homebrewhub)).

Is it an appreciated possibility to integrate our database in your 'Free homebrew games' Library?

**Comment by brianblakely** [comment]
It might be useful to put a link to https://gbhh.avivace.com/games in the library drawer.  What do you think?

**Comment by avivace** [comment]
I was thinking about having the entire Homebrew Hub library (or a subset, or just some categories/filters, or just the top rated) available in your app to play, no links. Just one click away to the games.

**Comment by brianblakely** [comment]
The problem with that is iOS has a hard limit for how much storage your app can consume.  I'd hate to take away from the user being able to add more games of their own choosing.

**Comment by brianblakely** [comment]
An additional idea: perhaps you could provide a list of MD5 hashes for all the software on HH, along with a string pattern for thumbnails.  That way, any ROMs added from HH will automatically fetch the correct artwork.  Tell me if that interests you (np if not).

BTW, thanks for maintaining Homebrew Hub.  Really nice work, and cool cool games.

**Comment by brianblakely** [comment]
Closing for now, but please feel free comment if/when you want to advance this issue.

**Comment by avivace** [comment]
cc @brianblakely Oh hey!
I've finally an alpha public API of Homebrew Hub, providing the entire game database as JSON, and exposing ROMs and screenshots (you can directly `fetch` those assets).

Are you still interested in this/have time?

Take a look at the quick [API documentation](https://gbhh.avivace.com/developers).

**Comment by brianblakely** [comment]
This is awesome!  With this, Atlantis could absolutely play homebrew games on-the-fly, and even "install" them for offline enjoyment.

Will pursue this.

**Comment by avivace** [comment]
Fantastic! Please let me know if you need help in anything or if the API feels weird in any way.

**Comment by brianblakely** [comment]
@avivace The API is easy to use.  Thanks so much.

Some ideas for the main homebrew list service, which naturally you may choose to implement or not:

* A `sortby` parameter for sorting homebrew results alphanumerically by the given field.
* A `filterby` parameter for limiting homebrew results to those which satisfy a key-value pair (or pairs).
* A `downloadCount` field, so users can gauge a particular homebrew's popularity level.

**Comment by avivace** [comment]
Yay! I'm glad you think that. :tada: 

Everything you mentioned makes sense, can you open an Issue on the [Homebrew Hub](https://github.com/gbdev/homebrewhub) repo? It'll be easier to track the suggestions and their implementation.

**Comment by avivace** [comment]
https://github.com/gbdev/homebrewhub/issues/23
https://github.com/gbdev/homebrewhub/issues/22
https://github.com/gbdev/homebrewhub/issues/21

**Comment by brianblakely** [comment]
@avivace Note that this was merged into master and will be deploying sometime in the next few weeks.

If you know how to use NPM, you can clone to run the emulator locally and take a look right now.

**Comment by brianblakely** [comment]
@avivace And by "next few weeks," I meant "over two years later." Wow, where does time go?

https://brianblakely.github.io/atlantis/

**Comment by avivace** [comment]
> @avivace And by "next few weeks," I meant "over two years later." Wow, where does time go?
> 
> https://brianblakely.github.io/atlantis/

Ahah, no worries. This looks so cool! Thank you!
