### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hunter1026** [brianblakely/atlantis#46]
**Describe the bug**
A clear and concise description of the bug.

when holding a button it selects stuff on the screen asking to copy or paste. 
blue stuff goes all over the screen making it hard to play please fix. i love the emulator except for this. 

**Did you add the app to the homescreen, if possible?**
yes
The app works best when launched from your homescreen.

**System Info:**
 - Device: [e.g. iPhone 8 Plus, Laptop]
 - OS: [e.g. iOS 12]
 - Browser [e.g. Chrome, Safari]
iphone 12 pro ios 16.2 safari 
**Screenshots**
If applicable, add screenshots to help exhibit the bug.

**Comment by brianblakely** [comment]
That should be imminently fixable. I'll look into it ASAP! Thanks for your report.

**Comment by hunter1026** [comment]
thanks ! glad you are going to fix it . let me know when its fixed plz.

**Comment by hunter1026** [comment]
are you still fixing this?

**Comment by brianblakely** [comment]
I am indeed. My dev machine just had to be reformatted last week, which I completed last night, so I'm sure I'll be able to address this very soon.

**Comment by hunter1026** [comment]
okay

**Comment by brianblakely** [comment]
This should be all fixed now.
